product.name=WSO2 Carbon
product.version=4.10.108
product.key=Carbon
carbon.product.version=4.10.108
carbon.version=4.10.108
default.server.role=CarbonServer
hotdeployment=true
hotupdate=true
childfirstCL=true
jaxwsparam=true
