product.name=WSO2 Carbon
product.version=4.10.102
product.key=Carbon
carbon.product.version=4.10.102
carbon.version=4.10.102
default.server.role=CarbonServer
hotdeployment=true
hotupdate=true
childfirstCL=true
jaxwsparam=true
